### ISSUE TITLE
Error shows up while using SAS kernel under Windows

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-sas#2]
As title. See the error below:
![captu1re](https://user-images.githubusercontent.com/26916551/37169742-5dce6016-22ce-11e8-853f-d4c7a8761bec.PNG)

**Comment by BoPeng** [comment]
You will have to consult [saspy](https://sassoftware.github.io/saspy/install.html) for appropriate communication method for windows.

**Comment by BoPeng** [comment]
stdio and stdio/ssh are available on the Linux platform only. Not sure how to configure [iom](https://sassoftware.github.io/saspy/install.html#iom) in your case.

**Comment by HenryLeongStat** [comment]
Referece here: https://github.com/vatlab/sos-sas/pull/3
