### ISSUE TITLE
Issue "getting" data from Python/R into SAS and vice versa

### ISSUE THREAD

**Issue by jrisi256** [vatlab/sos-sas#4]
Hi,

Thanks for making such a great tool!

I manage an RStudio Server Pro installation for a variety of users on RedHat 8. We have a variety of data scientists who work in R, Python, and SAS. Some people have expressed interest in using this tool in their workflows so I'm working to get it all setup for them. 

I have R versions 3.6.0 to 3.6.3 and Python versions 3.7.6 and 3.6.9. Additionally, I have SAS set-up.

On the SoS side, I have installed the following package using pip:

```
pip install sos sos-notebook sos-papermill sos-r sos-sas
```

I also have installed irkernel and feather for all versions of R AND saspy and sas_kernel for SAS. Each of the languages work fine on their own independently. R and Python are playing nice with each other. However, I cannot pass data to SAS (from any version of R or Python) nor can I get data from SAS (from any version of R or Python).

Below is what happens when I to pass data to SAS:

![image](https://user-images.githubusercontent.com/9837612/78617395-3249df00-7845-11ea-8a83-0d7f4208001e.png)

![image](https://user-images.githubusercontent.com/9837612/78617449-63c2aa80-7845-11ea-92c9-59c315130f86.png)

Below is what happens when I try to retrieve data from SAS:

![image](https://user-images.githubusercontent.com/9837612/78617500-9076c200-7845-11ea-9154-3b980aabd6bb.png)

I tried Googling around, but I couldn't really find anything helpful. Our set-up is pretty specific so if you need more information from me let me know.

**Comment by BoPeng** [comment]
@finkbine I have just released sos-sas version 0.19.0. It has been tested in our SAS environment (jupyterlab/mac + SAS/Linux) and should hopefully also work in yours. Please check the [updated `sos-sas` documentation](https://vatlab.github.io/sos-docs/doc/user_guide/sos_sas.html) for details and let me know if you encounter any more bug.

Note that remote `%get` from windows SAS servers will not work, but I will leave it for later.
